### ISSUE TITLE
License for audio generator script and language files

### ISSUE THREAD

**Issue by fvollmer** [dgiese/dustcloud#45]
I just noticed we don't have any license for the audio generator script and language files (at least as far as I can see). I guess we better fix this now than later. I would suggest [GPLv3](https://www.gnu.org/licenses/gpl-3.0-standalone.html) for the script and something open like the [CC0](https://creativecommons.org/publicdomain/zero/1.0/) for the actual translations.

Obviously we need every contributor to agree:
`generate_audio.py`:
- @fquinto
- @fvollmer
- @CODeRUS 
- @rudelm

`audio_ca.csv`:
 - @fquinto 

`audio_de.csv`:
 - @fvollmer
 - @dervitti 
 - @rudelm

`audio_en.csv`:
 - @fquinto

`audio_es.csv`
 - @fquinto

`audio_pl.csv`
 - @lemmure

What are your thoughts about this?

**Comment by lemmure** [comment]
Hi, accepted from my side (audio_pl.csv). 

Best regards 
Ekkehard 
Am 03.01.18, 10:13, fvollmer <notifications@github.com> schrieb:
I just noticed we don't have any license for the audio generator script and language files (at least as far as I can see). I guess we better fix this now than later. I would suggest GPLv3 for the script and something open like the CC0 for the actual translations.
Obviously we need every contributor to agree:
generate_audio.py:

@fquinto
@fvollmer
@CODeRUS
@rudelm

audio_ca.csv:

@fquinto

audio_de.csv:

@fvollmer
@dervitti
@rudelm

audio_en.csv:

@fquinto

audio_es.csv

@fquinto

audio_pl.csv

@lemmure

What are your thoughts about this?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dgiese/dustcloud","title":"dgiese/dustcloud","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dgiese/dustcloud"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"License for audio generator script and language files (#45)"}],"action":{"name":"View Issue","url":"https://github.com/dgiese/dustcloud/issues/45"}}}

**Comment by rudelm** [comment]
Hi,

accepted from my side for `generate_audio.py` with GPLv3 and `audio_de.csv` with CC0.

**Comment by dervitti** [comment]
Hi,
GPLv3 for the script and CC0 for the actual translations is OK for me.

**Comment by CODeRUS** [comment]
👍

**Comment by fquinto** [comment]
Hi, accepted from my side for languages EN, ES and CA.
